/**
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui;

import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui.AbstractLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LanguageUiModule extends AbstractLanguageUiModule {
  public LanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
