/**
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext;

import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.AbstractLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LanguageRuntimeModule extends AbstractLanguageRuntimeModule {
}
