/**
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext.scoping;

import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.scoping.AbstractLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class LanguageScopeProvider extends AbstractLanguageScopeProvider {
}
