/**
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui.contentassist;

import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui.contentassist.AbstractLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
