/**
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.web.AbstractLanguageWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LanguageWebModule extends AbstractLanguageWebModule {
  public LanguageWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
