/*
 * generated by Xtext 2.10.0
 */
package jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui;

import com.google.inject.Injector;
import jp.pizzafactory.modeling.dsl.vstepngt.ngtext.ui.internal.NgtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NgtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NgtextActivator.getInstance().getInjector(NgtextActivator.JP_PIZZAFACTORY_MODELING_DSL_VSTEPNGT_NGTEXT_LANGUAGE);
	}
	
}
